# Generated by Django 3.2.9 on 2021-11-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
