# Generated by Django 3.2.9 on 2021-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=1)),
                ('img_link', models.ImageField(upload_to=None)),
                ('nutri_values', models.TextField()),
                ('off_url', models.URLField(max_length=150)),
            ],
        ),
    ]
