# Generated by Django 3.2.9 on 2021-12-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
